### PR TITLE
Windows unittest framework

### PR DESCRIPTION
**Pull request by efu39**

### CODE REVIEW

**Comment by ericafu1122** [comment]
retest sinter-win,  please

**Comment by ericafu1122** [comment]
retest CI Tests (Windows), please

**Comment by efu39** [comment]
retest this please

**Review by smbillah — DISMISSED** [review]

**Comment by ericafu1122** [comment]
retest again please before merging

**Comment by efu39** [comment]
retest this please (try again before merging)

**Comment by efu39** [comment]
retest this please

**Comment by efu39** [comment]
retest this please

**Review by smbillah — DISMISSED** [review]

**Comment by ericafu1122** [comment]
retest this please

**Comment by efu39** [comment]
retest this please

**Comment by efu39** [comment]
retest this please

**Comment by ericafu1122** [comment]
> retest this please

**Comment by efu39** [comment]
retest this please

**Comment by efu39** [comment]
Finally done:)  'Sendkeys' has some user access issue in Jenkins, latest commit modifies registry to set the calculator layout. Now the testcases are passing in Jenkins consistently.

**Comment by efu39** [comment]
retest this please, final check

**Review by smbillah — APPROVED** [review]

**Review by smbillah — APPROVED** [review]

**Pull request merged**
